# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'merger2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from src.text import WINDOW_TITLE


class Ui_Merge(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(778, 503)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.btn_add = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.btn_add.setFont(font)
        self.btn_add.setObjectName("btn_add")
        self.gridLayout_3.addWidget(self.btn_add, 1, 0, 1, 3)
        self.lbl_name = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lbl_name.setFont(font)
        self.lbl_name.setObjectName("lbl_name")
        self.gridLayout_3.addWidget(self.lbl_name, 7, 0, 1, 1)
        self.txt_name = QtWidgets.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.txt_name.setFont(font)
        self.txt_name.setObjectName("txt_name")
        self.gridLayout_3.addWidget(self.txt_name, 7, 1, 1, 2)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.btn_up = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.btn_up.setFont(font)
        self.btn_up.setObjectName("btn_up")
        self.verticalLayout_2.addWidget(self.btn_up)
        self.btn_down = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.btn_down.setFont(font)
        self.btn_down.setObjectName("btn_down")
        self.verticalLayout_2.addWidget(self.btn_down)
        self.btn_delete = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.btn_delete.setFont(font)
        self.btn_delete.setObjectName("btn_delete")
        self.verticalLayout_2.addWidget(self.btn_delete)
        self.gridLayout_3.addLayout(self.verticalLayout_2, 3, 2, 1, 1)
        self.lst_pdf = QtWidgets.QListWidget(Dialog)
        self.lst_pdf.setObjectName("lst_pdf")
        self.gridLayout_3.addWidget(self.lst_pdf, 3, 0, 1, 2)
        self.btn_merge = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.btn_merge.setFont(font)
        self.btn_merge.setObjectName("btn_merge")
        self.gridLayout_3.addWidget(self.btn_merge, 11, 0, 1, 3)
        self.btn_back = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.btn_back.setFont(font)
        self.btn_back.setObjectName("btn_back")
        self.gridLayout_3.addWidget(self.btn_back, 0, 0, 1, 3)
        self.verticalLayout.addLayout(self.gridLayout_3)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", WINDOW_TITLE))
        self.btn_add.setText(_translate("Dialog", "Agregar pdf"))
        self.lbl_name.setText(_translate("Dialog", "Nombre archivo:"))
        self.btn_up.setText(_translate("Dialog", "Subir"))
        self.btn_down.setText(_translate("Dialog", "Bajar"))
        self.btn_delete.setText(_translate("Dialog", "Eliminar"))
        self.btn_merge.setText(_translate("Dialog", "Unir"))
        self.btn_back.setText(_translate("Dialog", "Return"))