# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'split.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Split(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.lbl_parts = QtWidgets.QLabel(Dialog)
        self.lbl_parts.setObjectName("lbl_parts")
        self.gridLayout.addWidget(self.lbl_parts, 2, 0, 1, 1)
        self.btn_back = QtWidgets.QPushButton(Dialog)
        self.btn_back.setObjectName("btn_back")
        self.gridLayout.addWidget(self.btn_back, 0, 0, 1, 3)
        self.btn_split = QtWidgets.QPushButton(Dialog)
        self.btn_split.setObjectName("btn_split")
        self.gridLayout.addWidget(self.btn_split, 3, 0, 1, 3)
        self.btn_loadfile = QtWidgets.QPushButton(Dialog)
        self.btn_loadfile.setObjectName("btn_loadfile")
        self.gridLayout.addWidget(self.btn_loadfile, 1, 2, 1, 1)
        self.lbl_filename = QtWidgets.QLabel(Dialog)
        self.lbl_filename.setObjectName("lbl_filename")
        self.gridLayout.addWidget(self.lbl_filename, 1, 0, 1, 2)
        self.box_pieces = QtWidgets.QSpinBox(Dialog)
        self.box_pieces.setObjectName("box_pieces")
        self.gridLayout.addWidget(self.box_pieces, 2, 1, 1, 2)
        self.horizontalLayout.addLayout(self.gridLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.lbl_parts.setText(_translate("Dialog", "Parts:"))
        self.btn_back.setText(_translate("Dialog", "Return"))
        self.btn_split.setText(_translate("Dialog", "Split"))
        self.btn_loadfile.setText(_translate("Dialog", "Load file"))
        self.lbl_filename.setText(_translate("Dialog", "Filename:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
