# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'win_main.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox


class Ui_Split(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.NonModal)
        Dialog.resize(494, 174)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.btn_split = QtWidgets.QPushButton(Dialog)
        self.btn_split.setObjectName("btn_split")
        self.gridLayout.addWidget(self.btn_split, 4, 0, 1, 3)
        self.lbl_pieces = QtWidgets.QLabel(Dialog)
        self.lbl_pieces.setObjectName("lbl_pieces")
        self.gridLayout.addWidget(self.lbl_pieces, 1, 0, 1, 1)
        self.lbl_filename = QtWidgets.QLabel(Dialog)
        self.lbl_filename.setObjectName("lbl_filename")
        self.gridLayout.addWidget(self.lbl_filename, 0, 0, 1, 2)
        self.btn_loadfile = QtWidgets.QPushButton(Dialog)
        self.btn_loadfile.setObjectName("btn_loadfile")
        self.gridLayout.addWidget(self.btn_loadfile, 0, 2, 1, 1)
        self.box_pieces = QtWidgets.QSpinBox(Dialog)
        self.box_pieces.setObjectName("box_pieces")
        self.box_pieces.setMinimum(2)
        self.box_pieces.setMaximum(99)
        self.gridLayout.addWidget(self.box_pieces, 1, 1, 1, 2)


        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)


    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "PDFSplit"))
        self.btn_split.setText(_translate("Dialog", "Separar archivo"))
        self.lbl_pieces.setText(_translate("Dialog", "Partes a separar:"))
        self.lbl_filename.setText(_translate("Dialog", "Nombre archivo:"))
        self.btn_loadfile.setText(_translate("Dialog", "Cargar archivo"))
